title: biobase-rs
description: Native Rust implementation of Biobase
url: "https://lifeissad21.github.io"
baseurl: "/biobase-rs"
theme: minima
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
    values:
      layout: default

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
